#-e DATA_CACHE_REFILLS_FROM_NORTHBRIDGE:10000
# -e CPU_CLK_UNHALTED:100000
# -e DATA_CACHE_ACCESSES:10000 -e DATA_CACHE_MISSES:10000 -e RETIRED_MISPREDICTED_BRANCH_INSTRUCTIONS:10000
operf  -e DATA_CACHE_REFILLS_FROM_L2_OR_NORTHBRIDGE:10000 -e DATA_CACHE_ACCESSES:10000 -e DATA_CACHE_MISSES:10000 -e RETIRED_MISPREDICTED_BRANCH_INSTRUCTIONS:10000  /home/laco/GitREPOS/SIMDCompressionAndIntersection/codecs --codecs streamvbyted1,streamvbyted1_old,copy,maskedvbyte,vbyte,varintgb --uniformdynamic